version: '2'
services:
    wetravelsouth-app:
        image: wetravelsouth
        external_links:
            - wetravelsouth-mysql:mysql
            - wetravelsouth-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/wetravelsouth?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    wetravelsouth-mysql:
        extends:
            file: mysql.yml
            service: wetravelsouth-mysql
    wetravelsouth-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: wetravelsouth-elasticsearch
