version: '2'
services:
    wetravelsouth-elasticsearch:
        container_name: wetravelsouth-elasticsearch
        image: elasticsearch:1.7.5
        # volumes:
        #     - ~/volumes/jhipster/WeTravelSouth/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
